version: '3'

services:
  db:
    image: postgres:latest
    container_name: weddingbuider_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weddingbuilder
    ports:
      - 5432:5432
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data

volumes:
  data:
  node_modules:
